PiPWeb/Controllers/RoadMapMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using K2.WebApi.Controllers;
using K2.WebApi.Helpers;
using K2.WebApi.Models;
using log4net;
using PiPWeb.Services;

namespace PiPWeb.Controllers
{
    public class RoadMapMasterController : Controller
    {
        RoadMapMastersApiController roadMapMastersApiController = new RoadMapMastersApiController();
        DocumentHelper helper = new DocumentHelper();
        // GET: /RoadMapMaster/
        protected static readonly ILog log = LogManager.GetLogger(typeof(RoadMapMastersApiController));
        ProductService productService = new ProductService();

        public async Task<ActionResult> Index()
        {
            try
            {
                helper.GivePermissionToFolder();
                await GetRoadMapMasters();
            }
            catch (Exception ex)
            {

                log.Error("Error " + ex);
            }
            return View();
        }

        public async Task<List<RoadMapMaster>> GetRoadMapMasters()
        {
            var roadMapMasterList = await productService.GetRoadMapMasterList();
            var newroadMapMasterList = roadMapMasterList.ToList();

                TempData.Keep("newroadMapMasterList");
                TempData["newroadMapMasterList"] = newroadMapMasterList;
                log.Info(newroadMapMasterList);
                return newroadMapMasterList;
        }

        public async Task<ActionResult> CreateRoadMapMaster(RoadMapMaster roadMapMasterInfo)
        {
            
            try
            {
                await roadMapMastersApiController.PostRoadMapMaster(roadMapMasterInfo);
                return Json(new { s = "Road Map Master has been successfully created." });
            }
            catch (Exception ex)
            {
                log.Error("Error occured in create Road Map Master " + ex);
                return Json(new { f = "Ooops!! something has gone wrong" });
            }


        }

        public async Task<ActionResult> UpdateRoadMapMaster(RoadMapMaster roadMapMasterInfo)
        {
            
            try
            {
                await roadMapMastersApiController.PutRoadMapMaster(roadMapMasterInfo.Id, roadMapMasterInfo);
                return Json(new { s = "Road Map Master has been successfully updated." });
                
            }
            catch (Exception ex)
            {
                log.Error("Error occured in updating Road Map Master " + ex);
                return Json(new { f = "Ooops!! something has gone wrong" });
            }
        }
    }
}

PiPWeb/Views/RoadMapMaster/Index.cshtml
@using K2.WebApi.Models
@model RoadMapMaster

@{
   
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Styles/sweetalert.css" rel="stylesheet" />
<link href="~/Content/themes/base/selectable.css" rel="stylesheet" />
<link href="~/Content/themes/base/autocomplete.css" rel="stylesheet" />
<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@*<link href="~/Content/themes/default/easyui.css" rel="stylesheet"/>*@
<link href="~/Content/chosen/chosen.min.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
@*<link href="~/Content/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>*@
<link href="~/Content/DataTables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/buttons.bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="~/Content/DataTables/css/dataTables.semanticui.min.css" rel="stylesheet" />
<section id="home">

        <div class="container">
            <div class="main-content">


                <div>

                    <div class="sub-green col-xs-12 mt20">
                        <h4>Road Map Form</h4>
                    </div>


                    <div class="col-xs-12 info">
                        @Html.Partial("~/Views/RoadMap/PartialUpdate.cshtml")

                        <div class="newRoadMap">
                                @using (Html.BeginForm("CreateRoadMapMaster", "RoadMapMaster", FormMethod.Post, new {id = "roadMasterForm"}))
                                {
                                    <p class="col-md-3 col-xs-12">
                                        <input type="text" class="form-control" placeholder="Road Map Name" id="RoadMapName" name="RoadMapName" required>
                                    </p>
                                    <p class="col-md-3 col-xs-12">
                                        <input type="text" class="form-control" placeholder="start Date" id="StartDate" name="StartDate" required>
                                    </p>
                                    <p class="col-md-3 col-xs-12">
                                        <input type="text" class="form-control" placeholder="End Date" id="EndDate" name="EndDate" required>
                                    </p>
                                            <div class="row">
            <div class="col-xs-12 form-group">
                <button type="submit" class="btn btn-success col-md-offset-1 col-md-2 col-xs-12 mr10">CANCEL</button>
                <button type="submit" class="btn  btn-success col-md-2 col-xs-12" id="submitFrm">SUBMIT</button>
            </div>
        </div>
                                }
                        </div>
                        <p></p>

                        <div class="col-xs-12 info" style="padding-top: 0; padding-right: 0; padding-left: 0;">
                            <table class="table" style="border: 0; height: auto;" id="datagrid">
                                <thead>
                                <tr>
                                    <th class="hide"></th>
                                    <th>Road Map Name (Example: Q1 2017, Q2 2017, ...)</th>
                                    <th>Start Date</th>
                                    <th>End Date</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody>
                                @{

                                    var newroadMapMasterList = new List<RoadMapMaster>();
                                    if (TempData["newroadMapMasterList"] != null)
                                    {
                                        newroadMapMasterList = (List<RoadMapMaster>)TempData["newroadMapMasterList"];
                                        foreach (var item in newroadMapMasterList)
                                        {
                                            <tr>
                                                <td class="hide">@item.Id</td>
                                                <td>@item.RoadMapName</td>
                                                <td>@item.StartDate.ToString("dd-MMM-yyyy")</td>
                                                <td>@item.EndDate.ToString("dd-MMM-yyyy")</td>
                                                <td><a class="update" href="#">Edit</a></td>
                                            </tr>
                                        }
                                    }

                                }
                                </tbody>
                            </table>
                        </div>
                    </div>

                   

                </div>


            </div>

        </div>
        
    

</section>
<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/sweetalert.min.js"></script>

<script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
<script src="~/Scripts/DataTables/dataTables.bootstrap.min.js"></script>
<script src="~/Scripts/DataTables/dataTables.buttons.min.js"></script>

<script src="~/Content/chosen/chosen.jquery.min.js"></script>
<script src="~/Content/chosen/chosen.proto.min.js"></script>
<script>
    $(function () {

        $('#datagrid').DataTable();

        $("#submitFrm").css("display", "block");
        $("#updateFrm").css("display", "none");
        $(".newRoadMap").css("display", "block");
        $(".updateRoadMap").css("display", "none");

        $("#StartDate, #EndDate, #updateStartDate, #updateEndDate").datepicker({
            dateFormat: 'dd-M-yy'
        });

        $('#roadMasterForm').submit(function () {
            $('#submitFrm').attr('disabled', 'disabled');
            
            $.ajax({
                type: this.method,
                url: this.action,
                data: $(this).serialize(),
                success: function (result) {
                    if (result.s != null) {
                        swal(result.s, "", "success");
                        $('#submitFrm').removeAttr('disabled');
                        top.location.href = "/RoadMapMaster";
                    }
                    else if (result.f != null) {
                        $('#submitFrm').removeAttr('disabled');
                        swal(result.f, "", "error");
                    }
                }
            });

            return false;

            //var addRow = "<tr><td><input type='checkbox' name='record'></td><td>" + roadMapName_ + "</td><td>" + startDate_ + "</td><td>" + endDate_ + "</td><td><a class='update' href='#'>Edit</a></td></tr>";
            //$("table tbody").append(addRow);
            //$("#roadMapName").val("");
            //$("#startDate").val("");
            //$("#endDate").val("");
            //compact();
            //document.location.href = "/";
        });
        //var rid = 0;

        $(".update").click(function () {
            var tableEditRow = $('#datagrid tr').eq($('#datagrid tr').index($(this).parents('tr')));
            $('#updateRoadMapName').val(tableEditRow.children("td").eq(1).html());
            $('#updateStartDate').val(tableEditRow.children("td").eq(2).html());
            $('#updateEndDate').val(tableEditRow.children("td").eq(3).html());
            //rid = tableEditRow.children("td").eq(0).html();
            $('#Id').val(tableEditRow.children("td").eq(0).html());
            $("#submitFrm").css("display", "none");
            $("#updateFrm").css("display", "block");

            $(".newRoadMap").css("display", "none");
            $(".updateRoadMap").css("display", "block");
        });


        // Find and remove selected table rows
        $('#roadMasterFormUpdate').submit(function () {
            $(".updateRoadMap").attr('disabled', 'disabled');
            $.ajax({
                type: this.method,
                url: this.action,
                data: $(this).serialize(),
                dataType: 'json',

                success: function (result) {
                    if (result.f != null) {
                        $('.updateRoadMap').removeAttr('disabled');
                        swal(result.f, "", "error");

                    } else if (result.s != null) {
                        $('.updateRoadMap').removeAttr('disabled');
                        swal(result.s, "", "success");
                        top.location.href = "/RoadMapMaster";
                    }

                }
            });
            return false;
        });



    });
</script>

PiPWeb/Views/RoadMapMaster/PartialUpdate.cshtml
@model K2.WebApi.Models.RoadMapMaster
<div class="updateRoadMap">
    @using (Html.BeginForm("UpdateRoadMapMaster", "RoadMapMaster", FormMethod.Post, new { id = "roadMasterFormUpdate" }))
    {
        <p class="col-md-3 col-xs-12"></p>
        <p class="col-md-3 col-xs-12">
            <input type="text" id="Id" name="Id" />
            <input type="text" class="form-control" placeholder="Road Map Name" id="updateRoadMapName" name="RoadMapName" required>
        </p>
        <p class="col-md-3 col-xs-12">
            <input type="text" class="form-control" placeholder="start Date" id="updateStartDate" name="StartDate" required>
        </p>
        <p class="col-md-3 col-xs-12">
            <input type="text" class="form-control" placeholder="End Date" id="updateEndDate" name="EndDate" required>
        </p>
        
        <div class="col-xs-12 form-group">
                <button type="submit" class="btn btn-success col-md-offset-1 col-md-2 col-xs-12 mr10">CANCEL</button>
                <button type="submit" class="btn btn-success col-md-2 col-xs-12" id="updateFrm">Update</button>
       </div>
    }
</div>