PiPWeb/Controllers/ImplementationController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Xml;
using K2.WebApi.Controllers;
using K2.WebApi.Helpers;
using K2.WebApi.Models;
using log4net;
using PiPWeb.Helper;
using PiPWeb.Services;
using SourceCode.Workflow.Client;

namespace PiPWeb.Controllers
{
    public class ImplementationController : Controller
    {

        // GET: /Implementation/

        protected static readonly ILog log = LogManager.GetLogger(typeof(ProductController));
        ProductService productService = new ProductService();

        string tag = ConfigurationManager.AppSettings["ProdImplTAG"];
        string brdTag = ConfigurationManager.AppSettings["BRDTAG"]; 
        DocumentHelper helper = new DocumentHelper();
        string apiUrl = ConfigurationManager.AppSettings["apiUrl"];

        public async Task<ActionResult> AddNewImplimentationTimeLine(ImplementationTimeline impTimelIne)
        {
            try
            {
                var brdInfo = await productService.GetBrdInfoByRequestId(impTimelIne.RequestId);

                long ImplimentationInfoId = await CreateImplimentationInfo(brdInfo.ConceptInfoId, brdInfo.ConceptInfoId, brdInfo.RequestId, impTimelIne.SN);

                if (ImplimentationInfoId == 0)
                {
                    log.Error("Error in adding new Implimentation timeline. Implimentation Info Creation returns 0 as Id ");
                    return Json(new { f = "Ooops!! something has gone wrong" });
                }
                impTimelIne.ImplementationInfoId = ImplimentationInfoId;

                await new ImplementationTimelinesApiController().PostImplementationTimeline(impTimelIne);

                var newImplTimeline = new List<ImplementationTimeline>();

                newImplTimeline = await productService.GetProductImplTimeListByRequestId(impTimelIne.RequestId);


                var countOfRows = newImplTimeline.Count();

                var lastRow = newImplTimeline.Skip(countOfRows - 1).FirstOrDefault();


                return Json(new { s = "New Implimentation timeline row added!", id = lastRow.Id });
            }
            catch (Exception ex)
            {
                log.Error("Error in adding new Implimentation timeline " + ex);
                return Json(new { f = "Ooops!! something has gone wrong" });
            }
        }

        public async Task<ActionResult> RemoveImplimentationTimeLine(long id)
        {
            try
            {
                await new ImplementationTimelinesApiController().DeleteImplementationTimeline(id);
                return Json(new { s = "Row deleted!" });
            }
            catch (Exception ex)
            {
                log.Error("Error in deleting Implimentation timeline " + ex);
                return Json(new { f = "Ooops!! something has gone wrong" });
            }
        }

        public async Task<long> CreateImplimentationInfo(long brdInfoId, long conceptId, string requestId, string sn)
        {
            var implementationInfo = new ImplementationInfo();
            try
            {
                implementationInfo = new ImplementationInfo
                {
                    BrdInfoId = brdInfoId,
                    ConceptId = conceptId,
                    RequestId = requestId,
                    SN = sn,
                    Tag = tag
                };


                var newImplimentationInfo = new ImplementationInfo();
                newImplimentationInfo = await productService.GetImplementationInfoByRequestIdandTag(implementationInfo.RequestId, tag);

                if (newImplimentationInfo == null)
                {
                    await new ImplementationInfosApiController().PostImplementationInfo(implementationInfo);
                }

                newImplimentationInfo = await productService.GetImplementationInfoByRequestIdandTag(implementationInfo.RequestId, tag);
                var lastRowId = newImplimentationInfo.Id;

                return lastRowId;
            }
            catch (Exception ex)
            {
                log.Error("Error in adding new Implimentation Info " + ex);
                return 0;
            }
        }

        [Authorize]
        public async Task<ActionResult> Index(string SN)
        {
            string impersonatedUser = @"K2:" + User.Identity.Name;
            var brdInfo = new BrdInfo();
            var k2ActionList = new List<string>();
            using (var connection = new Connection())
            {
                try
                {
                    connection.Open("localhost");
                    connection.ImpersonateUser(impersonatedUser);

                    WorklistItem worklistItem = connection.OpenWorklistItem(SN);

                    var requestId = (string) worklistItem.ProcessInstance.DataFields["RequestId"].Value;
                    //febf323c6090
                   // var requestId = "febf323c6090";
                    brdInfo = await productService.GetBrdInfoByRequestId(requestId);

                    brdInfo.SN = worklistItem.SerialNumber;
                    //brdInfo.SN = SN;

                    var slaCategoryInfoList = await productService.GetSlaCategoryList();
                    var slaCategoryList = slaCategoryInfoList.Where(x => x.SlaLevel == tag).ToList();
                    
                    TempData.Keep("slaCategoryList");
                    TempData["slaCategoryList"] = slaCategoryList;

                    long roadMapId = (long) brdInfo.RoadMapId;
                    RoadMap roadMapInfo = await productService.GetRoadMapInfoById(roadMapId);
                    RoadMapMaster roadMapMasterInfo = await productService.GetRoadMapMasterInfoByRoadMapMasterId(roadMapInfo.RoadMapMasterId);

                    TempData.Keep("roadMapInfo");
                    TempData["roadMapInfo"] = roadMapInfo;

                    TempData.Keep("roadMapMasterInfo");
                    TempData["roadMapMasterInfo"] = roadMapMasterInfo;


                    var stakeHolders = await productService.GetStakeHolderInfoById(brdInfo.Stakeholder);
                    TempData.Keep("stakeHolders");
                    TempData["stakeHolders"] = stakeHolders;

                    //BRD Stage
                    var implimenatationInfoBrd = await productService.GetImplementationInfoByRequestIdandTag(brdInfo.RequestId, brdTag);
                    if (implimenatationInfoBrd != null)
                    {
                        var BrdprodImplTimelineList = await productService.GetImplementationTimeListByImplementationId(implimenatationInfoBrd.Id);
                        TempData.Keep("BrdprodImplTimelineList");
                        TempData["BrdprodImplTimelineList"] = BrdprodImplTimelineList;
                    }

                    //Implementation Stage
                    var implimenatationInfo = await productService.GetImplementationInfoByRequestIdandTag(brdInfo.RequestId, tag);

                    if (implimenatationInfo != null)
                    {
                        var prodImplTimelineList = await productService.GetImplementationTimeListByImplementationId(implimenatationInfo.Id);
                        TempData.Keep("prodImplTimelineList");
                        TempData["prodImplTimelineList"] = prodImplTimelineList;
                    }

                    var actionHistory = new List<ActionHistoryInfo>();

                    actionHistory = await productService.GetActionHistoryInfoListByRequestId(brdInfo.RequestId);

                    TempData.Keep("actionHistory");
                    TempData["actionHistory"] = actionHistory;

                    var documentInfoList = await productService.GetDocumentInfoListByRequestId(brdInfo.RequestId);
                    TempData.Keep("documentInfoList");
                    TempData["documentInfoList"] = documentInfoList;
                    

                    await LoadAllAdUser();
                    
                    TempData.Keep("K2ActionName");
                    //foreach (SourceCode.Workflow.Client.Action k2Action in worklistItem.Actions)
                    //{
                    //    k2ActionList.Add(k2Action.Name);
                    //}
                    k2ActionList.Add("Reject");
                    k2ActionList.Add("Assign");
                    TempData["K2ActionName"] = k2ActionList;
                }
                catch (Exception ex)
                {
                     log.Error("Error Loading Implementation Stage WorkListItem to Approve BRD. " + ex);
                    
                }
                connection.Close();
            }
            return View(brdInfo);
            
        }

        public async Task<ActionResult> ApproveBrdRequest(string SN, string requestId, string approvalAction, string taskAsssignedTo, string approverComment, string taskPriority, string slaCategory)
        {
            string impersonatedUser = @"K2:" + User.Identity.Name;
           
            var brdInfo = new BrdInfo();
            var actionHistory = new List<ActionHistoryInfo>();
            ActionHistoryInfo logActionHistory = new ActionHistoryInfo();

           

            BrdInfosApiController brdApi = new BrdInfosApiController();
            using (var connection = new Connection())
            {
                RoleHelper userRole = new RoleHelper();
                try
                {
                    //Log Action History
                    
                    connection.Open("localhost");
                    connection.ImpersonateUser(impersonatedUser);
                    WorklistItem worklistItem = connection.OpenWorklistItem(SN);
                    worklistItem.ProcessInstance.DataFields["DestinationUser"].Value = impersonatedUser;
                     
                     brdInfo = await productService.GetBrdInfoByRequestId(requestId);

PiPWeb/Views/Implementation/implUpdate.cshtml
@using System.Web.Script.Serialization
@using K2.WebApi.Models
@using Microsoft.AspNet.Identity
@model dynamic
@{
   
    Layout = "~/Views/Shared/_Layout.cshtml";
    //var theId = Guid.NewGuid().ToString().Replace("-", "").Substring(0, 12);
    //var theId = "882a0447e998";
}



<section id="home">
                <div class="green-header"><h4>BRD Stage Initiation Page</h4></div>

    <div class="container">
        <div class="main-content">


            <div>

                @using (Html.BeginForm("CreateBrd", "Product", FormMethod.Post, new { id = "brdFrm", role = "form" }))
                {


                    <div class="col-xs-12 info" style="margin-top: 5px;">
                        <p class="col-md-4 col-xs-12"></p>
                        <input type="hidden" value="BRD" id="tag" name="tag"/> 
                        <input type="hidden" id="requestId" name="requestId" value=""/>


                    </div>

                    <div class="sub-green col-xs-12 mt20">
                            <h4 class="pull-left">Production Implementation Timelines</h4>
                            <i class="fa fa-chevron-up pull-right pt10"></i>
                            </div>
                    <div class="col-xs-12 info" style="padding-top: 0; padding-right: 0; padding-left: 0;">
                        <table class="table" style="border: 0; height: auto;" id="datagrid">
                            <thead>
                            <tr>
                                <th  class="hide">ID</th>
                                <th>Tag</th>
                                <th>Initiator</th>
                                <th>Status</th>
                                <th>Date Paused</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                                                        @{
                    var pim = new List<PauseInfo>();
                    if (TempData["pauseInfoList"] != null)
                    {
                        pim = (List<PauseInfo>)TempData["pauseInfoList"];


                    }

                    foreach (var item in pim)
                    {
                                <tr>
                                    <td class="hide">@item.Id</td>
                                    <td>@item.Tag</td>
                                    <td>@item.Actor</td>
                                    <td>@item.Status</td>
                                    <td>@item.DatePaused.ToString("dd MMM \\'yy")</td>
                                    <td><button style=""  type="button" class="btn btn-info resume">Resume</button></td>
                                </tr>


                    }


                        }
                            </tbody>
                        </table>
                    </div>


                    <div class="col-xs-12 form-group" style="margin-top:20px; float:right;">
                    </div>

                }
            </div>
           
        </div>
    </div>

</section>
<script>
    function ShowDocumentDiv() {
        //alert("Boo");
        var documentDiv = document.getElementById('documentDiv');
        var documentSelect = document.getElementById('documentTypeId_chosen');

        documentDiv.style.display = "inline";
        documentSelect.style.width = '120px';
        //document.getElementById("buttonNext").setAttribute('disabled', true);

    }


    $(function() {
        $('#brdFrm').submit(function() {
            //alert("Booo");
            var fields = $(this).serializeArray();
            var activities = compact();
            fields.push({ name: 'Activities', value: JSON.stringify(activities)});
            $.ajax({              
                url: this.action,
                type: this.method,
                data: fields,
                success: function(result) {
                    //debugger;

                    if (result.f != null) {

                        swal(result.f, "!", "error");

                    } else {


                        swal({
                            title: "Success!",
                            text: result.s,
                            type: "success"
                        });

                        ShowDocumentDiv();
                    }

                }
            });

            return false;
        });
    });
</script>





<script>

    $("#datepicker, #st,#stp").datepicker();
    $(".chosen-select").chosen({ no_results_text: "Oops, nothing found!" }, { max_selected_options: 5 }, { width: "30%" });


 
   
        $(".resume").click(function () {
            $cells = $(this).closest("tr").children('td.hide').text();
                $.ajax({
                    url: '/Activities/Update?pauseRef=' + $cells,
                    type: "POST",
                    //data: fields,
                    success: function (result) {

                        if (result.f != null) {

                            swal(result.f, "!", "error");

                        } else {


                            swal({
                                title: "Success!",
                                text: result.s,
                                type: "success"
                            });

                        }

                    }
                });

                return false;
            }); 
</script>

PiPWeb/Views/Implementation/implapproval.cshtml
@using System.Web.Script.Serialization
@using K2.WebApi.Models
@using Microsoft.AspNet.Identity

@{
    
    Layout = "~/Views/Shared/_Layout.cshtml";



    var apiUrl = (string)TempData["apiUrl"];

    var conceptDetails = new ConceptInfo();
    if (TempData["conceptInfo"] != null)
    {
        conceptDetails = (ConceptInfo)TempData["conceptInfo"];


    }
}
<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<link href="~/Styles/sweetalert.css" rel="stylesheet"/>
<link href="~/Content/toastr.min.css" rel="stylesheet" />
<script src="~/Scripts/sweetalert.min.js"></script>
<script src="~/Scripts/toastr.min.js"></script>
<section id="home">
<div class="green-header">
    <h4>BRD Draft Stage Page</h4>
</div>
    @{
        var user = new ADModel();
    }
    <div class="container">
        <div class="main-content">
            <div>

                @using (Html.BeginForm("ActionApproval", "Implementation", FormMethod.Post, new { id = "brdFrm", role = "form" }))
                {

                    
                    <div class="sub-green col-xs-12 mt20">
                        <h4>Concept Details</h4>
                    </div>
                    <div class="col-xs-12 info">
                        <p class="col-md-4 col-xs-12">Concept Owner</p>
                        <p class="col-md-4 col-xs-12">Concept Initiator</p>
                        <p class="col-md-4 col-xs-12">Product Description</p>



                        @{
                   
                            <p class="col-md-4 col-xs-12">@conceptDetails.ConceptOwner</p>
                            <p class="col-md-4 col-xs-12">@conceptDetails.OriginatorUserName</p>
                            <p class="col-md-4 col-xs-12">@conceptDetails.ProductDescription</p>



                        }
                    </div>
                    <div class="sub-green col-xs-12 mt20">
                        <h4 class="pull-left">Attached Documents</h4>
                        <i class="fa fa-chevron-up pull-right pt10"></i>
                    </div>
                    <div class="col-xs-12 info" style="padding-top: 0; padding-right: 0; padding-left: 0;">
                        <table class="table" style="border: 0; height: auto;">
                            <thead>
                            <tr>
                                <th>File</th>
                                <th>Description</th>
                            </tr>
                            </thead>
                            <tbody>
                            @{
                    var attchedfiles = new List<DocumentInfo>();
                    if (TempData["documentInfoList"] != null)
                    {
                        attchedfiles = (List<DocumentInfo>)TempData["documentInfoList"];
                    }
                    foreach (var item in attchedfiles)
                    {
                        var docDesc = item.DocumentDescription != null ? item.DocumentDescription : "NA";
                                    <tr>
                                        <td><a href="@item.DocumentPath" target="_blank">@item.DocumentName</a></td>

                                        <td>@docDesc</td>
                                    </tr>
                    }
                            }
                            </tbody>
                        </table>

                    </div>
                    
                                        <div class="sub-green col-xs-12 mt20">
                        <h4 class="pull-left">Action History</h4>
                        <i class="fa fa-chevron-up pull-right pt10"></i>
                    </div>
                    <div class="col-xs-12 info" style="padding-top: 0; padding-right: 0; padding-left: 0;">
                        <table class="table" style="border: 0; height: auto;">
                            <thead>
                            <tr>
                                <th>Arrival Time</th>
                                <th>Action Time</th>
                                <th>Activity</th>
                                <th>Action</th>
                                <th>Participant</th>
                                <th>Destination User</th>
                                <th>Comment</th>
                            </tr>
                            </thead>
                            <tbody>
                            @{
                    var actionHistory = new List<ActionHistoryInfo>();
                    if (TempData["actionHistory"] != null)
                    {
                        actionHistory = (List<ActionHistoryInfo>)TempData["actionHistory"];
                        foreach (var item in actionHistory)
                        {
                                        <tr>
                                            <td>@item.WorkListArrivalTime.Value.ToString("dd MMM \\'yy")</td>
                                            <td>@item.ActionTimeStamp.Value.ToString("dd MMM \\'yy")</td>
                                            <td>@item.Activity</td>
                                            <td>@item.Action</td>
                                            <td>@item.Participant</td>
                                            <td>@item.DestinationUser</td>
                                            <td>@item.Comment</td>
                                        </tr>
                        }
                    }

                            }
                            </tbody>
                        </table>

                    </div>
                    
                    <div class="sub-green col-xs-12 mt20">
                        <h4 class="pull-left">Implementation Timeline Details</h4>
                        <i class="fa fa-chevron-up pull-right pt10"></i>
                    </div>
                    <div class="col-xs-12 info" style="padding-top: 0; padding-right: 0; padding-left: 0;">
                        <table class="table" style="border: 0; height: auto;">
                            <thead>
                                <tr>
                                    <th>TimeLine Start Date</th>
                                    <th>TimeLine End Date</th>
                                    <th>Activity Name</th>
                                    <th>Description</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                    var implementation = new List<ImplementationTimeline>();
                    if (TempData["implementation"] != null)
                    {
                        implementation = (List<ImplementationTimeline>)TempData["implementation"];
                        foreach (var item in implementation)
                        {
                                    <tr>
                                        <td>@item.TimelineStartDate.ToString("dd MMM \\'yy")</td>
                                        <td>@item.TimelineEndDate.ToString("dd MMM \\'yy")</td>
                                        <td>@item.ActivityName</td>
                                        <td>@item.Description</td>
                                    </tr>
                        }
                    }
                   
                                }
                            </tbody>
                        </table>

                    </div>




                    <div class="col-md-12"style="margin-bottom:12px;"></div>
                    <div class="prodTimeLine">




                        <p></p>
                        <div class="col-xs-12 info">
                            <div class="form-group col-md-3 col-xs-12">
                                <label>Action</label><br>
                                @{
                    if (TempData["K2ActionName"] != null)
                    {
                        var actionName = (List<string>)TempData["K2ActionName"];
                

                                        <select id="status" name="action" class="form-control dropdown" style="width: 180px;">
                                            @foreach (var item in actionName)
                                            {
                                                <option value="@item">@item</option>
                                            }
                                        </select>}
                                        }
                                
                               
                            </div>
                            </div>

                    </div>
                    <p class="col-xs-12 form-group"></p>
                    <div class="col-xs-12 form-group">
                        <button type="submit" class="btn  btn-success col-md-2 col-xs-12" id="submitBrdFrm">SUBMIT</button>
                    </div>
                }
            </div>

        </div>
    </div>

</section>
<script>

$('#brdFrm').submit(function() {
    $.ajax({
        url: this.action,
        type: this.method,
        data: this.serialize(),
        cache: false,
        dataType: "json",
        success: function (result) {

            if (result.f != null) {

                swal(result.f, "!", "error");

            } else {
                swal({
                    title: "Success!",
                    text: result.s,
                    type: "success"
                });
            }
        }
    });

});
            

</script>